apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zalando
  namespace: argocd
  annotations:
    kubernetes.io/description: |
      This Application installs the Zalando Postgres Operator, which sets up and automates Postgres clusters.
      
      This application points to the Zalando postgres-operator Helm repo.
      To update Zalando PGO to a new major or minor release, change the targetRevision tag to a new release tag.
      https://argo-cd.readthedocs.io/en/stable/user-guide/trackin g_strategies/#helm
    jlh.name/upstream: https://github.com/zalando/postgres-operator
spec:
  project: default
  source:
    chart: postgres-operator
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    targetRevision: 1.10.*
    helm:
      releaseName: zalando-pgo
      parameters:
        # Adds ARM64 support https://github.com/zalando/postgres-operator/releases/tag/v1.10.0
        # Not yet available for Zalando UI https://github.com/zalando/postgres-operator/issues/1940#issuecomment-1555998746
        - name: "image.registry"
          value: "ghcr.io"
        - name: "image.repository"
          value: "zalando/postgres-operator"
        - name: "configKubernetes.enable_pod_antiaffinity"  # https://postgres-operator.readthedocs.io/en/latest/administrator/#enable-pod-anti-affinity
          value: "true"
  destination:
    name: in-cluster
    namespace: 'zalando'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
