apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-apps
  namespace: argocd
  annotations:
    kubernetes.io/description: |
      This is the "app of apps" for the custom_applications subdirectory.
      It loads root-appset, which in turn loads everything else in that directory.
spec:
  project: default
  source:
    repoURL: git@codeberg.org:jlh/lemmies.git
    targetRevision: HEAD
    path: 'argo/custom_applications'
  destination:
    name: in-cluster
    namespace: 'argocd'
  syncPolicy:
    automated: {}
