apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-apps
  namespace: argocd
  annotations:
    kubernetes.io/description: |
      This is the "app of apps" for the external_applications subdirectory.
      It loads all of the applications in that directory.
spec:
  project: default
  source:
    repoURL: git@codeberg.org:jlh/lemmies.git
    targetRevision: HEAD
    path: 'argo/external_applications'
  destination:
    name: in-cluster
    namespace: 'argocd'
  syncPolicy:
    automated: {}
