apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-install
  namespace: argocd
  annotations:
    kubernetes.io/description: |
      This Application manages ArgoCD's own installation. It points to ArgoCD's install manifest on Github.
      
      This Application automatically installs new "patch" releases as they're pushed to the release branch. 
      To update ArgoCD to a new major or minor release, change the targetRevision branch to a new release branch.
    jlh.name/upstream: https://github.com/argoproj/argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-cd.git
    targetRevision: release-2.7
    path: 'manifests/'
    directory:
      include: install.yaml
  destination:
    name: in-cluster
    namespace: 'argocd'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: ConfigMap  # Allow overwriting ArgoCD configuration from other Applications
      jsonPointers:
        - /data
        - /metadata/labels
