apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
  annotations:
    kubernetes.io/description: |
      This Applicationset loads all directories inside custom_applications.
      
      How this app of apps pattern works:
      Each directory here triggers ArgoCD's git generator, which creates a new Application for each directory.
      The Application will be named after the directory, and will create a namespace with the given directory.
      All resources defined in the directory will be created in the given namespace, 
      if the resource doesn't specify its own namespace in its metadata.
      
      (Separate, limited-scope ArgoCD instances should be used if you want to restrict namespaces accessible from GitOps for security purposes, 
      just having 1 application per namespace does not provide a security boundary.)
spec:
  generators:
  - git:
      repoURL: git@codeberg.org:jlh/lemmies.git
      revision: HEAD
      directories:
      - path: argo/custom_applications/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@codeberg.org:jlh/lemmies.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
